[project]
name = "gaokao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "html2text>=2025.4.15",
    "neo4j>=5.28.1",
    "nest-asyncio>=1.6.0",
    "playwright>=1.52.0",
    "python-dotenv>=1.1.0",
]
